Basic music player
posneg/yolamtan_bot pull request #6
Opened 2022-01-07 03:10 UTC by ambern115

It plays youtube links!
Its organized better?

2022-01-07 03:11 UTC, ambern115 commented
Theres probably still some junk left over from testing stuff that I could still remove.

2022-01-07 18:23 UTC, posneg commented
I'll be looking into this PR tomorrow

2022-01-09 23:20 UTC, posneg requested changes
Most of the changes look good -- I think really the thing I'd like to see the most is logging, as that'll help debug any issues that arise later.

You can see some existing examples of logging in some of the code I've written, and you can use the bot's logger or you can create a music player specific log/handler.

2022-01-09 23:20 UTC, posneg commented on bot/music_player/player.py
> +        #return cls(discord.FFmpegPCMAudio(filename, **ffmpeg_options), data=data)
Let's remove the extra line here

2022-01-31 03:11 UTC, posneg commented on bot/music_player/player_cog.py
> +    async def play_local(self, ctx, song_name, filter=""):
If you want to use multiword song names without quotation marks, you can remove the filter (perhaps make the filter a command per-guild?) argument and use the following function definition instead.
```suggestion
    async def play_local(self, ctx, *, song_name):
```

2022-02-04 00:11 UTC, posneg commented on bot/music_player/player_cog.py
> +    async def play_local(self, ctx, song_name, filter=""):
After discussion, this sort of change would be in a separate PR.  We'll leave that for later and accept as-is.

2022-02-04 00:12 UTC, posneg approved these changes
LGTM for now

2022-02-04 00:16 UTC, merged